### ISSUE TITLE
Minor game title fix

### ISSUE THREAD

**Issue by inadra9** [TwitchPlaysPokemon/musicLibrary#14]
It's my first time here so I want to ask first.

A while ago I submitted songs using the [music submission form](https://twitchplayspokemon.tv/music_submission_form). I was sure that I put the game title as "Dragon Ball: Advanced Adventure", with a colon. But when the songs show up on stream (and when searching for them using !song), the game name is shown as "Dragon Ball Advanced Adventure", without a colon.

Since the colon is in the official name of the game, I'd like to ask for it to be added.

**Comment by Felk** [comment]
I opened a pull request for this, see https://github.com/TwitchPlaysPokemon/musicLibrary/pull/15

**Comment by Torq-A** [comment]
as this pull has been added into the main system, this issue can be closed out.
