### ISSUE TITLE
FYI: Pokemon Sun/Moon OST is already out

### ISSUE THREAD

**Issue by mslabo102** [TwitchPlaysPokemon/musicLibrary#2]
https://itunes.apple.com/us/album/pokemon-sun-pokemon-moon-super/id1173163741

**Comment by hlixed** [comment]
Way ahead of you! Sun and Moon music was added 4 days ago. Thanks for letting us know, though!

**Comment by mslabo102** [comment]
I already knew SuMo is in. It was for title's cause.

**Comment by hlixed** [comment]
Ah, OK. No harm in making it an issue, then.

**Comment by mslabo102** [comment]
This was first time using github so nvm

**Comment by hlixed** [comment]
Don't worry about it, and welcome to github!

**Comment by ProjectRevoTPP** [comment]
Why is this an issue? You already have S/M tracks in. Closing this. do not reopen.
