### ISSUE TITLE
Shovel Knight is now Shovel Knight: Treasure Trove

### ISSUE THREAD

**Issue by slashiee** [TwitchPlaysPokemon/musicLibrary#3]
As of the release of Specter of Torment, Shovel Knight was renamed to Shovel Knight: Treasure Trove, as indicated on pretty much every store. (ex. [Steam](http://store.steampowered.com/app/250760/Shovel_Knight_Treasure_Trove/), [eShop](https://www.nintendo.com/games/detail/shovel-knight-treasure-trove-switch), [Microsoft Store](https://www.microsoft.com/en-us/store/p/shovel-knight-treasure-trove/bpfvsms2mn7l), [Playstation Store](https://store.playstation.com/#!/en-us/games/shovel-knight-treasure-trove/cid=UP2200-CUSA01867_00-SHOVELKNIGHT0001), [official website](http://yachtclubgames.com/shovel-knight/))

I know it's not really a huge deal to change it, but it's probably something to consider in the long run.

**Comment by sunkhaskasis** [comment]
fixed

**Comment by sunkhaskasis** [comment]
UPD: I was misinformed. We've decided to keep it as "Shovel Knight" for now. However, once someone submits the music from Specter of Torment, we'll change the title.
