### ISSUE TITLE
Some of the Grand Theft Auto: San Andreas songs are actually Royalty-free songs

### ISSUE THREAD

**Issue by WhatAboutGaming** [TwitchPlaysPokemon/musicLibrary#4]
```
id: bike_boat_results
title: "Bike and Boat School Level Results"
path: "Bike and Boat School Level Results.brstm"
type: result
```
https://www.youtube.com/watch?v=pNzNDjqTa_U
Song name: One More Yard by Westar Music (In video description)

```
id: driving_results
title: "Driving School Level Results"
path: "Driving School Level Results.brstm"
type: result
```
https://www.youtube.com/watch?v=EJ0fTR9HB9w
Westar Music S.A. (In video description)

```
id: saint_mark_bistro
title: "Saint Mark's Bistro"
path: "Saint Mark's Bistro.brstm"
type: break
```
https://www.youtube.com/watch?v=0qHEaudV8bw
https://www.grandtheftwiki.com/Saint_Mark%27s_Bistro
The music heard inside the restaurant is Tchaikovsky's Serenade for Strings. (In the grandtheftwiki link)

**Comment by boombafunk** [comment]
Thanks for bringing it to our attention. The songs are subject to removal.
